os: 
  - osx
  - linux
language: ruby
install: true

env: 
  - |
    XCAKE_CI_TASKS=TEST

gemfile:
  - Gemfile
  - gemfiles/Gemfile.xcodeproj-edge
rvm:
  - 2.3.3
  - 2.4.0
  - 2.5.0
  - 2.6.0
  - 2.7.0

matrix:
  include:
  - rvm: 2.7.0
    os: linux
    env: XCAKE_CI_TASKS=LINT

before_script:
  - gem install bundler -v "~> 1.17"
  - bundle install --jobs=3
