os: osx
language: ruby
install: true

env: 
  - |
    XCAKE_CI_TASKS=TEST JFROG_CLI_OFFER_CONFIG=false

gemfile:
  - Gemfile
  - gemfiles/Gemfile.xcodeproj-edge
rvm:
  - 2.5.0
  - ruby-2.0.0-p648

before_script:
  - gem install bundler -v "~> 1.17"
  - bundle install --jobs=3
  - curl -fL https://getcli.jfrog.io | sh
  - sudo mv jfrog /usr/bin/jfrog

script:
  - ./ci.sh
