os:
  - osx
language: ruby

matrix:
  include:
  - rvm: 2.5.0
    env: XCAKE_CI_TASKS=LINT
    git:
      submodules: false

env: XCAKE_CI_TASKS=TEST

gemfile:
  - Gemfile
  - gemfiles/Gemfile.xcodeproj-edge
rvm:
  - 2.5.0
  - ruby-2.0.0-p648

addons:
 code_climate:
   repo_token: ce53533c444ac133e8b0b15e988c1b5c3af1aecabb41da49e11bfb4ca2131f34
